language: go

go:
  - 1.13.x
go_import_path: ./2019_2_Next_Level
branches:
  only:
  - master
  - develop
script:
  - eval "$(ssh-agent -s)"
  - pwd
  - ls
#  - cp -avr scripts/ build/
#  - cp -avr config/ build/
  - mkdir deploy
  - cp -avr scripts/ deploy/
  - cp -avr config/ deploy/
  - ssh-keyscan -H 84.201.153.27 >> ~/.ssh/known_hosts
  - ssh-keyscan -H 193.109.79.141 >> ~/.ssh/known_hosts
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - make
  - cp -avr build/ deploy/
  - scp -i ./deploy_key -r ./deploy/scripts ian@84.201.153.27:/home/ian/deploy/
  - ssh -i ./deploy_key -t ian@84.201.153.27 "cd ./deploy/scripts; chmod +x stopall.sh && ./stopall.sh && ls"
  - scp -i ./deploy_key -r ./deploy/* ian@84.201.153.27:/home/ian/deploy/
  - scp -i ./deploy_key -r ./deploy/scripts/* root@mail.nl-mail.ru:~/deploy/scripts/
  - ssh -i ./deploy_key -t root@mail.nl-mail.ru "cd ./deploy/scripts; chmod +x stopall.sh && ./stopall.sh"
  - ssh -i ./deploy_key -t ian@84.201.153.27 "cd ./deploy/scripts; chmod +x runall.sh && nohup ./runall.sh"
  - ssh -i ./deploy_key -t root@mail.nl-mail.ru "cd ./deploy/; nohup ./build/post_service -config ./config/post_service.config.json"
before_install:
  - openssl aes-256-cbc -K $encrypted_363a4fc03002_key -iv $encrypted_363a4fc03002_iv
    -in deploy_key.enc -out ./deploy_key -d
  - ls
#  - makeg