language: go

go:
  - 1.x
  - "1.13"
  - 1.13.x
script:
  - eval "$(ssh-agent -s)"
  - ssh-keyscan -H 84.201.153.27 >> ~/.ssh/known_hosts
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key ian@84.201.153.27 pwd
  - scp -i ./deploy_key -r ./* ian@84.201.153.27:/home/ian/deploy/ && \
    go build -o build/auth_service cmd/Auth/main.go && \
    go build -o build/mailpicker_service cmd/MailPicker/main.go && \
    go build -o build/http_service cmd/serverapi/main.go &&\
    kill $(pgrep ../build -f) && cd ./scripts && chmod +x runall.sh && ./runall.shg
before_install:
  - openssl aes-256-cbc -K $encrypted_363a4fc03002_key -iv $encrypted_363a4fc03002_iv
    -in deploy_key.enc -out ./deploy_key -d