language: go

go:
  - 1.13.x
go_import_path: ./2019_2_Next_Level
branches:
  only:
  - master
  - develop
script:
  - eval "$(ssh-agent -s)"
  - pwd
  - ls
#  - cp -avr scripts/ build/
#  - cp -avr config/ build/
  - mkdir deploy
  - cp -avr scripts/ deploy/
  - cp -avr config/ deploy/
  - ssh-keyscan -H mail.nl-mail.ru >> ~/.ssh/known_hosts
  - ssh-keyscan -H nl-mail.ru >> ~/.ssh/known_hosts
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - make
  - cp -avr build/ deploy/
  - scp -i ./deploy_key -r ./deploy/scripts ian@nl-mail.ru:/home/ian/deploy/
  - scp -i ./deploy_key -o "StrictHostKeyChecking=no" -r ./deploy/scripts root@mail.nl-mail.ru:/root/deploy/
  - ssh -i ./deploy_key -t ian@nl-mail.ru "cd ./deploy/scripts; chmod +x stopall.sh && ./stopall.sh && ls"
  - ssh -i ./deploy_key -o "StrictHostKeyChecking=no" -t root@mail.nl-mail.ru "cd ./deploy/scripts; chmod +x stopall.sh && ./stopall.sh"
  - sleep 10
  - scp -i ./deploy_key -o "StrictHostKeyChecking=no" -r ./deploy/* root@mail.nl-mail.ru:/root/deploy/
  - ssh -i ./deploy_key -o "StrictHostKeyChecking=no" -t root@mail.nl-mail.ru "cd ./deploy/; chmod +x scripts/post.sh && nohup scripts/post.sh"
  - scp -i ./deploy_key -r ./deploy/* ian@nl-mail.ru:/home/ian/deploy/
  - sleep 5
  - ssh -i ./deploy_key -t ian@nl-mail.ru "cd ./deploy/scripts; chmod +x runall.sh && nohup ./runall.sh"
before_install:
  - openssl aes-256-cbc -K $encrypted_363a4fc03002_key -iv $encrypted_363a4fc03002_iv
    -in deploy_key.enc -out ./deploy_key -d
  - ls
#  - makeg