language: go

go:
  - 1.13.x
go_import_path: ./2019_2_Next_Level
branches:
  only:
  - master
  - develop
script:
  - eval "$(ssh-agent -s)"
  - pwd
  - ls
  - cp -avr scripts/ build/
  - cp -avr config/ build/
  - ssh-keyscan -H 84.201.153.27 >> ~/.ssh/known_hosts
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key ian@84.201.153.27 pwd
  - scp -i ./deploy_key -r ./build ian@84.201.153.27:/home/ian/deploy/
#  - ssh -i ./deploy_key ian@84.201.153.27 cd ./deploy/build/scripts && chmod +x runall.sh && ./runall.sh
  - ssh -i ./deploy_key -t ian@84.201.153.27 "cd ./deploy/build/scripts; chmod +x runall.sh && ./runall.travis.gsh"
before_install:
  - openssl aes-256-cbc -K $encrypted_363a4fc03002_key -iv $encrypted_363a4fc03002_iv
    -in deploy_key.enc -out ./deploy_key -d
  - rm -rf build/*