// Code generated by MockGen. DO NOT EDIT.
// Source: repository.mailpicker.mock.go

// Package repository is a generated GoMock package.
package auth

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetLoginBySession mocks base method
func (m *MockRepository) GetLoginBySession(uuid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginBySession", uuid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginBySession indicates an expected call of GetLoginBySession
func (mr *MockRepositoryMockRecorder) GetLoginBySession(uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginBySession", reflect.TypeOf((*MockRepository)(nil).GetLoginBySession), uuid)
}

// AddNewSession mocks base method
func (m *MockRepository) AddNewSession(login, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewSession", login, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewSession indicates an expected call of AddNewSession
func (mr *MockRepositoryMockRecorder) AddNewSession(login, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewSession", reflect.TypeOf((*MockRepository)(nil).AddNewSession), login, uuid)
}

// DeleteSession mocks base method
func (m *MockRepository) DeleteSession(uuiв string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", uuiв)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession
func (mr *MockRepositoryMockRecorder) DeleteSession(uuiв interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockRepository)(nil).DeleteSession), uuiв)
}

// DeleteUserSessions mocks base method
func (m *MockRepository) DeleteUserSessions(login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSessions", login)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSessions indicates an expected call of DeleteUserSessions
func (mr *MockRepositoryMockRecorder) DeleteUserSessions(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSessions", reflect.TypeOf((*MockRepository)(nil).DeleteUserSessions), login)
}

// GetUserCredentials mocks base method
func (m *MockRepository) GetUserCredentials(login string) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCredentials", login)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserCredentials indicates an expected call of GetUserCredentials
func (mr *MockRepositoryMockRecorder) GetUserCredentials(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCredentials", reflect.TypeOf((*MockRepository)(nil).GetUserCredentials), login)
}

// UpdateUserPassword mocks base method
func (m *MockRepository) UpdateUserPassword(login string, newPassword, sault []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", login, newPassword, sault)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword
func (mr *MockRepositoryMockRecorder) UpdateUserPassword(login, newPassword, sault interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockRepository)(nil).UpdateUserPassword), login, newPassword, sault)
}
