// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package config

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecode20192NextLevelInternalMailPickerConfig(in *jlexer.Lexer, out *Database) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Port":
			out.Port = string(in.String())
		case "Host":
			out.Host = string(in.String())
		case "DBName":
			out.DBName = string(in.String())
		case "User":
			out.User = string(in.String())
		case "Password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncode20192NextLevelInternalMailPickerConfig(out *jwriter.Writer, in Database) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Port\":"
		out.RawString(prefix[1:])
		out.String(string(in.Port))
	}
	{
		const prefix string = ",\"Host\":"
		out.RawString(prefix)
		out.String(string(in.Host))
	}
	{
		const prefix string = ",\"DBName\":"
		out.RawString(prefix)
		out.String(string(in.DBName))
	}
	{
		const prefix string = ",\"User\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	{
		const prefix string = ",\"Password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Database) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncode20192NextLevelInternalMailPickerConfig(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Database) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncode20192NextLevelInternalMailPickerConfig(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Database) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecode20192NextLevelInternalMailPickerConfig(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Database) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecode20192NextLevelInternalMailPickerConfig(l, v)
}
func easyjson6615c02eDecode20192NextLevelInternalMailPickerConfig1(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "RemotePort":
			out.RemotePort = string(in.String())
		case "RemoteHost":
			out.RemoteHost = string(in.String())
		case "remoteCheckTimeout":
			out.RemoteCheckTimeout = int16(in.Int16())
		case "pickerWorkerCount":
			out.PickerWorkerCount = int(in.Int())
		case "CleanerWorkerCount":
			out.CleanerWorkerCount = int(in.Int())
		case "SaverWorkerCount":
			out.SaverWorkerCount = int(in.Int())
		case "Database":
			(out.DB).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncode20192NextLevelInternalMailPickerConfig1(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"RemotePort\":"
		out.RawString(prefix[1:])
		out.String(string(in.RemotePort))
	}
	{
		const prefix string = ",\"RemoteHost\":"
		out.RawString(prefix)
		out.String(string(in.RemoteHost))
	}
	{
		const prefix string = ",\"remoteCheckTimeout\":"
		out.RawString(prefix)
		out.Int16(int16(in.RemoteCheckTimeout))
	}
	{
		const prefix string = ",\"pickerWorkerCount\":"
		out.RawString(prefix)
		out.Int(int(in.PickerWorkerCount))
	}
	{
		const prefix string = ",\"CleanerWorkerCount\":"
		out.RawString(prefix)
		out.Int(int(in.CleanerWorkerCount))
	}
	{
		const prefix string = ",\"SaverWorkerCount\":"
		out.RawString(prefix)
		out.Int(int(in.SaverWorkerCount))
	}
	{
		const prefix string = ",\"Database\":"
		out.RawString(prefix)
		(in.DB).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncode20192NextLevelInternalMailPickerConfig1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncode20192NextLevelInternalMailPickerConfig1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecode20192NextLevelInternalMailPickerConfig1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecode20192NextLevelInternalMailPickerConfig1(l, v)
}
