// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package httperror

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5fa5a888Decode20192NextLevelInternalServerapiServerHttpError(in *jlexer.Lexer, out *HttpResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		case "error":
			(out.Err).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5fa5a888Encode20192NextLevelInternalServerapiServerHttpError(out *jwriter.Writer, in HttpResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	if !in.isEmpty {
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		(in.Err).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HttpResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5fa5a888Encode20192NextLevelInternalServerapiServerHttpError(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HttpResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5fa5a888Encode20192NextLevelInternalServerapiServerHttpError(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HttpResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5fa5a888Decode20192NextLevelInternalServerapiServerHttpError(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HttpResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5fa5a888Decode20192NextLevelInternalServerapiServerHttpError(l, v)
}
func easyjson5fa5a888Decode20192NextLevelInternalServerapiServerHttpError1(in *jlexer.Lexer, out *HttpError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int(in.Int())
		case "msg":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5fa5a888Encode20192NextLevelInternalServerapiServerHttpError1(out *jwriter.Writer, in HttpError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HttpError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5fa5a888Encode20192NextLevelInternalServerapiServerHttpError1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HttpError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5fa5a888Encode20192NextLevelInternalServerapiServerHttpError1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HttpError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5fa5a888Decode20192NextLevelInternalServerapiServerHttpError1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HttpError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5fa5a888Decode20192NextLevelInternalServerapiServerHttpError1(l, v)
}
