// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Email struct {
	From                 string   `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Email) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Email) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Empty struct {
	S                    bool     `protobuf:"varint,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func (m *Empty) GetS() bool {
	if m != nil {
		return m.S
	}
	return false
}

type StringResult struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringResult) Reset()         { *m = StringResult{} }
func (m *StringResult) String() string { return proto.CompactTextString(m) }
func (*StringResult) ProtoMessage()    {}
func (*StringResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *StringResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringResult.Unmarshal(m, b)
}
func (m *StringResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringResult.Marshal(b, m, deterministic)
}
func (m *StringResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringResult.Merge(m, src)
}
func (m *StringResult) XXX_Size() int {
	return xxx_messageInfo_StringResult.Size(m)
}
func (m *StringResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StringResult.DiscardUnknown(m)
}

var xxx_messageInfo_StringResult proto.InternalMessageInfo

func (m *StringResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *StringResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type StatusResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResult) Reset()         { *m = StatusResult{} }
func (m *StatusResult) String() string { return proto.CompactTextString(m) }
func (*StatusResult) ProtoMessage()    {}
func (*StatusResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *StatusResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResult.Unmarshal(m, b)
}
func (m *StatusResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResult.Marshal(b, m, deterministic)
}
func (m *StatusResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResult.Merge(m, src)
}
func (m *StatusResult) XXX_Size() int {
	return xxx_messageInfo_StatusResult.Size(m)
}
func (m *StatusResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResult.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResult proto.InternalMessageInfo

func (m *StatusResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type String struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ChangePasswordMessage struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	OldPass              string   `protobuf:"bytes,2,opt,name=OldPass,proto3" json:"OldPass,omitempty"`
	NewPass              string   `protobuf:"bytes,3,opt,name=NewPass,proto3" json:"NewPass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordMessage) Reset()         { *m = ChangePasswordMessage{} }
func (m *ChangePasswordMessage) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordMessage) ProtoMessage()    {}
func (*ChangePasswordMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ChangePasswordMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordMessage.Unmarshal(m, b)
}
func (m *ChangePasswordMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordMessage.Marshal(b, m, deterministic)
}
func (m *ChangePasswordMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordMessage.Merge(m, src)
}
func (m *ChangePasswordMessage) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordMessage.Size(m)
}
func (m *ChangePasswordMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordMessage proto.InternalMessageInfo

func (m *ChangePasswordMessage) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ChangePasswordMessage) GetOldPass() string {
	if m != nil {
		return m.OldPass
	}
	return ""
}

func (m *ChangePasswordMessage) GetNewPass() string {
	if m != nil {
		return m.NewPass
	}
	return ""
}

type CredentialsMessage struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialsMessage) Reset()         { *m = CredentialsMessage{} }
func (m *CredentialsMessage) String() string { return proto.CompactTextString(m) }
func (*CredentialsMessage) ProtoMessage()    {}
func (*CredentialsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CredentialsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialsMessage.Unmarshal(m, b)
}
func (m *CredentialsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialsMessage.Marshal(b, m, deterministic)
}
func (m *CredentialsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialsMessage.Merge(m, src)
}
func (m *CredentialsMessage) XXX_Size() int {
	return xxx_messageInfo_CredentialsMessage.Size(m)
}
func (m *CredentialsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialsMessage proto.InternalMessageInfo

func (m *CredentialsMessage) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *CredentialsMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Email)(nil), "service.Email")
	proto.RegisterType((*Empty)(nil), "service.Empty")
	proto.RegisterType((*StringResult)(nil), "service.StringResult")
	proto.RegisterType((*StatusResult)(nil), "service.StatusResult")
	proto.RegisterType((*String)(nil), "service.String")
	proto.RegisterType((*ChangePasswordMessage)(nil), "service.ChangePasswordMessage")
	proto.RegisterType((*CredentialsMessage)(nil), "service.CredentialsMessage")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0x7c, 0x77, 0x44, 0xdd, 0x6a, 0x5b, 0x2a, 0x8b, 0x56, 0x55, 0xb5, 0xa7, 0x9e, 0x38,
	0xb4, 0x97, 0x88, 0x4b, 0x14, 0x4c, 0x50, 0x22, 0xe5, 0x4b, 0x86, 0x1c, 0x72, 0x5c, 0xf0, 0xca,
	0x38, 0x31, 0x5e, 0xb4, 0xb3, 0x0e, 0xe2, 0x4f, 0xe4, 0x37, 0x47, 0xbb, 0x5e, 0x03, 0x21, 0x21,
	0x0a, 0xb7, 0x79, 0x3b, 0xef, 0xbd, 0xf1, 0xcc, 0x93, 0xe1, 0x33, 0x72, 0xf9, 0x18, 0x4f, 0x79,
	0x77, 0x21, 0x85, 0x12, 0xa4, 0x61, 0x21, 0xbd, 0x83, 0xda, 0xe9, 0x9c, 0xc5, 0x09, 0x21, 0x50,
	0x1d, 0x4a, 0x31, 0xf7, 0x9c, 0x3f, 0xce, 0xdf, 0x4f, 0x81, 0xa9, 0x89, 0x0b, 0xe5, 0xb1, 0xf0,
	0xca, 0xe6, 0xa5, 0x3c, 0x16, 0xc4, 0x83, 0xc6, 0x28, 0x9b, 0xdc, 0xf3, 0xa9, 0xf2, 0x2a, 0xe6,
	0xb1, 0x80, 0x5a, 0xdd, 0x17, 0xe1, 0xca, 0xab, 0xe6, 0x6a, 0x5d, 0xd3, 0xb6, 0xb6, 0x5e, 0xa8,
	0x15, 0x69, 0x81, 0x83, 0xc6, 0xb7, 0x19, 0x38, 0x48, 0x7b, 0xd0, 0x1a, 0x29, 0x19, 0xa7, 0x51,
	0xc0, 0x31, 0x4b, 0x14, 0xf9, 0x01, 0xf5, 0xbc, 0xb2, 0xa3, 0x2d, 0xd2, 0x96, 0xbe, 0x08, 0xb9,
	0x19, 0x5f, 0x0b, 0x4c, 0x4d, 0xa9, 0xd6, 0x32, 0x95, 0xe1, 0x0e, 0xc7, 0xd9, 0xe2, 0xfc, 0x82,
	0x7a, 0xee, 0xaf, 0xbb, 0x03, 0xa6, 0x58, 0xb1, 0x92, 0xae, 0x29, 0x83, 0xb6, 0x3f, 0x63, 0x69,
	0xc4, 0x6f, 0x18, 0xe2, 0x52, 0xc8, 0xf0, 0x92, 0x23, 0xb2, 0x88, 0x93, 0xef, 0x50, 0xbb, 0x10,
	0x51, 0x9c, 0x5a, 0x76, 0x0e, 0xf4, 0xc6, 0xd7, 0x49, 0xa8, 0xb9, 0xf6, 0x0c, 0x05, 0xd4, 0x9d,
	0x2b, 0xbe, 0x34, 0x1d, 0x7b, 0x0b, 0x0b, 0xe9, 0x10, 0x88, 0x2f, 0x79, 0xc8, 0x53, 0x15, 0xb3,
	0x04, 0xdf, 0xf7, 0xef, 0x40, 0xb3, 0xf8, 0x10, 0x3b, 0x60, 0x8d, 0xff, 0x3d, 0x55, 0xa0, 0x7a,
	0x92, 0xa9, 0x19, 0xe9, 0x81, 0x6b, 0xd8, 0xfd, 0xd5, 0x88, 0x23, 0xc6, 0x22, 0x25, 0x5f, 0xba,
	0x45, 0x9c, 0xf9, 0xaa, 0x9d, 0xf6, 0xce, 0x43, 0x7e, 0x1f, 0x5a, 0x22, 0x47, 0xe6, 0x62, 0x52,
	0x1d, 0xae, 0xec, 0x81, 0x3b, 0xe0, 0xa8, 0xa4, 0xf8, 0xd8, 0xd4, 0x4d, 0x2a, 0xb4, 0x44, 0x8e,
	0xe1, 0x9b, 0xd5, 0xde, 0x22, 0x97, 0x56, 0x8f, 0x07, 0x18, 0x9c, 0x83, 0xfb, 0x32, 0x26, 0xf2,
	0x7b, 0x4d, 0x7d, 0x33, 0xbf, 0xfd, 0x56, 0x67, 0xf0, 0xd5, 0x9f, 0xf1, 0xe9, 0xc3, 0x56, 0x26,
	0xe4, 0xe7, 0xc6, 0xec, 0x55, 0x52, 0x7b, 0x9d, 0x26, 0x75, 0xf3, 0xef, 0xfc, 0x7f, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x0d, 0xdd, 0x45, 0x44, 0x4c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	LoginBySession(ctx context.Context, in *String, opts ...grpc.CallOption) (*StringResult, error)
	StartSession(ctx context.Context, in *String, opts ...grpc.CallOption) (*StringResult, error)
	DestroySession(ctx context.Context, in *String, opts ...grpc.CallOption) (*StatusResult, error)
	DestroyUserSessions(ctx context.Context, in *String, opts ...grpc.CallOption) (*StatusResult, error)
	ChangePassword(ctx context.Context, in *ChangePasswordMessage, opts ...grpc.CallOption) (*StatusResult, error)
	CheckCredentials(ctx context.Context, in *CredentialsMessage, opts ...grpc.CallOption) (*StatusResult, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) LoginBySession(ctx context.Context, in *String, opts ...grpc.CallOption) (*StringResult, error) {
	out := new(StringResult)
	err := c.cc.Invoke(ctx, "/service.Auth/LoginBySession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) StartSession(ctx context.Context, in *String, opts ...grpc.CallOption) (*StringResult, error) {
	out := new(StringResult)
	err := c.cc.Invoke(ctx, "/service.Auth/StartSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) DestroySession(ctx context.Context, in *String, opts ...grpc.CallOption) (*StatusResult, error) {
	out := new(StatusResult)
	err := c.cc.Invoke(ctx, "/service.Auth/DestroySession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) DestroyUserSessions(ctx context.Context, in *String, opts ...grpc.CallOption) (*StatusResult, error) {
	out := new(StatusResult)
	err := c.cc.Invoke(ctx, "/service.Auth/DestroyUserSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ChangePassword(ctx context.Context, in *ChangePasswordMessage, opts ...grpc.CallOption) (*StatusResult, error) {
	out := new(StatusResult)
	err := c.cc.Invoke(ctx, "/service.Auth/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CheckCredentials(ctx context.Context, in *CredentialsMessage, opts ...grpc.CallOption) (*StatusResult, error) {
	out := new(StatusResult)
	err := c.cc.Invoke(ctx, "/service.Auth/CheckCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	LoginBySession(context.Context, *String) (*StringResult, error)
	StartSession(context.Context, *String) (*StringResult, error)
	DestroySession(context.Context, *String) (*StatusResult, error)
	DestroyUserSessions(context.Context, *String) (*StatusResult, error)
	ChangePassword(context.Context, *ChangePasswordMessage) (*StatusResult, error)
	CheckCredentials(context.Context, *CredentialsMessage) (*StatusResult, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) LoginBySession(ctx context.Context, req *String) (*StringResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginBySession not implemented")
}
func (*UnimplementedAuthServer) StartSession(ctx context.Context, req *String) (*StringResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (*UnimplementedAuthServer) DestroySession(ctx context.Context, req *String) (*StatusResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySession not implemented")
}
func (*UnimplementedAuthServer) DestroyUserSessions(ctx context.Context, req *String) (*StatusResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyUserSessions not implemented")
}
func (*UnimplementedAuthServer) ChangePassword(ctx context.Context, req *ChangePasswordMessage) (*StatusResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedAuthServer) CheckCredentials(ctx context.Context, req *CredentialsMessage) (*StatusResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCredentials not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_LoginBySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).LoginBySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Auth/LoginBySession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).LoginBySession(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Auth/StartSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).StartSession(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Auth/DestroySession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).DestroySession(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_DestroyUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).DestroyUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Auth/DestroyUserSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).DestroyUserSessions(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Auth/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ChangePassword(ctx, req.(*ChangePasswordMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CheckCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CheckCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Auth/CheckCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CheckCredentials(ctx, req.(*CredentialsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginBySession",
			Handler:    _Auth_LoginBySession_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _Auth_StartSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _Auth_DestroySession_Handler,
		},
		{
			MethodName: "DestroyUserSessions",
			Handler:    _Auth_DestroyUserSessions_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Auth_ChangePassword_Handler,
		},
		{
			MethodName: "CheckCredentials",
			Handler:    _Auth_CheckCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
