// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package Auth

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC0e5e3f1Decode20192NextLevelInternalAuth(in *jlexer.Lexer, out *AuthClient) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0e5e3f1Encode20192NextLevelInternalAuth(out *jwriter.Writer, in AuthClient) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AuthClient) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0e5e3f1Encode20192NextLevelInternalAuth(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AuthClient) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0e5e3f1Encode20192NextLevelInternalAuth(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AuthClient) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0e5e3f1Decode20192NextLevelInternalAuth(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AuthClient) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0e5e3f1Decode20192NextLevelInternalAuth(l, v)
}
